"""Report generation for CiviQual Stats.

Generates self-contained HTML reports that can be opened in a browser or
printed to PDF from the browser. HTML is used rather than a dedicated PDF
library to keep the dependency footprint on the standard SciPy stack.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Optional

import base64
import io

from matplotlib.figure import Figure

from version import __app_name__, __version__


_CSS = """
@page { size: letter; margin: 0.75in; }
body { font-family: Georgia, 'Times New Roman', serif; color: #1f1f1f; max-width: 7.5in; margin: 0 auto; }
h1 { color: #6d132a; border-bottom: 3px solid #dcad73; padding-bottom: 6px; }
h2 { color: #6d132a; margin-top: 1.5em; }
.brand { color: #dcad73; font-size: 10pt; }
table { border-collapse: collapse; width: 100%; margin: 1em 0; font-size: 10pt; }
th, td { padding: 6px 10px; border-bottom: 1px solid #b2b2b2; text-align: left; }
th { background: #6d132a; color: #ffffff; }
.meta { color: #6d6d6d; font-size: 9pt; }
.chart { margin: 1em 0; text-align: center; }
.chart img { max-width: 100%; border: 1px solid #b2b2b2; }
.footer { margin-top: 2em; border-top: 1px solid #b2b2b2; padding-top: 6px; color: #6d6d6d; font-size: 8.5pt; }
.signal { color: #c0392b; font-weight: bold; }
"""


def _figure_to_b64_png(fig: Figure) -> str:
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=140, bbox_inches="tight")
    return base64.b64encode(buf.getvalue()).decode("ascii")


class ReportBuilder:
    def __init__(self, title: str, author: str = ""):
        self.title = title
        self.author = author
        self._sections: list[str] = []

    def add_paragraph(self, text: str) -> None:
        self._sections.append(f"<p>{text}</p>")

    def add_heading(self, text: str, level: int = 2) -> None:
        self._sections.append(f"<h{level}>{text}</h{level}>")

    def add_table(self, headers: list[str], rows: list[list]) -> None:
        thead = "".join(f"<th>{h}</th>" for h in headers)
        body = ""
        for r in rows:
            cells = "".join(f"<td>{c}</td>" for c in r)
            body += f"<tr>{cells}</tr>"
        self._sections.append(f"<table><thead><tr>{thead}</tr></thead><tbody>{body}</tbody></table>")

    def add_figure(self, fig: Figure, caption: str = "") -> None:
        b64 = _figure_to_b64_png(fig)
        img = f'<img src="data:image/png;base64,{b64}" />'
        cap = f"<div class='meta'>{caption}</div>" if caption else ""
        self._sections.append(f"<div class='chart'>{img}{cap}</div>")

    def render(self) -> str:
        ts = datetime.now().strftime("%Y-%m-%d %H:%M")
        sections_html = "\n".join(self._sections)
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{self.title}</title>
<style>{_CSS}</style>
</head>
<body>
<div class="brand">{__app_name__} v{__version__}</div>
<h1>{self.title}</h1>
<div class="meta">Author: {self.author or "(not specified)"} &middot; Generated {ts}</div>
{sections_html}
<div class="footer">
Generated by {__app_name__} v{__version__}. Interpretation of results requires
qualified judgment. This report is for analytical purposes and is not a
substitute for professional statistical or engineering advice.
</div>
</body>
</html>
"""
        return html

    def save(self, path: str | Path) -> Path:
        path = Path(path)
        path.write_text(self.render(), encoding="utf-8")
        return path
