#!/usr/bin/env python3
"""
CiviQual Report Generator

Generates analysis reports in Word and HTML formats.

Copyright (c) 2025 A Step in the Right Direction LLC
All Rights Reserved.
"""

from pathlib import Path
from datetime import datetime

try:
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.style import WD_STYLE_TYPE
    DOCX_AVAILABLE = True
except ImportError:
    DOCX_AVAILABLE = False


class ReportGenerator:
    """Report generation for CiviQual."""
    
    # CiviQual Brand Colors (as RGB tuples)
    BURGUNDY = RGBColor(109, 19, 42) if DOCX_AVAILABLE else None
    GOLD = RGBColor(220, 173, 115) if DOCX_AVAILABLE else None
    
    def __init__(self):
        """Initialize the report generator."""
        pass
    
    def generate_report(self, output_path, data, stats_engine, charts=None):
        """
        Generate a comprehensive analysis report.
        
        Args:
            output_path: Path for output file
            data: pandas DataFrame with analysis data
            stats_engine: StatisticsEngine instance with results
            charts: Optional list of chart image paths
            
        Returns:
            str: Path to generated report
        """
        path = Path(output_path)
        
        if path.suffix.lower() == '.html':
            return self._generate_html_report(path, data, stats_engine, charts)
        else:
            return self._generate_docx_report(path, data, stats_engine, charts)
    
    def _generate_docx_report(self, output_path, data, stats_engine, charts=None):
        """Generate Word document report."""
        if not DOCX_AVAILABLE:
            raise ImportError("python-docx is required for Word reports. "
                            "Install with: pip install python-docx")
        
        doc = Document()
        
        # Title
        title = doc.add_heading('CiviQual Analysis Report', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Subtitle with date
        subtitle = doc.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = subtitle.add_run(f'Generated: {datetime.now().strftime("%Y-%m-%d %H:%M")}')
        run.italic = True
        
        doc.add_paragraph()  # Spacer
        
        # Data Summary Section
        doc.add_heading('Data Summary', level=1)
        
        summary_para = doc.add_paragraph()
        summary_para.add_run(f'Total Observations: ').bold = True
        summary_para.add_run(f'{len(data)}\n')
        summary_para.add_run(f'Number of Columns: ').bold = True
        summary_para.add_run(f'{len(data.columns)}\n')
        summary_para.add_run(f'Numeric Columns: ').bold = True
        numeric_cols = data.select_dtypes(include=['number']).columns.tolist()
        summary_para.add_run(f'{len(numeric_cols)}\n')
        
        # Add charts if provided
        if charts:
            doc.add_heading('Analysis Charts', level=1)
            for chart_path in charts:
                if Path(chart_path).exists():
                    doc.add_picture(chart_path, width=Inches(6))
                    doc.add_paragraph()
        
        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph()
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = footer.add_run('Generated by CiviQual Statistical Analysis Tool')
        run.italic = True
        run.font.size = Pt(9)
        
        run2 = footer.add_run('\n© 2025 A Step in the Right Direction LLC')
        run2.font.size = Pt(8)
        
        doc.save(output_path)
        return str(output_path)
    
    def _generate_html_report(self, output_path, data, stats_engine, charts=None):
        """Generate HTML report."""
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CiviQual Analysis Report</title>
    <style>
        body {{
            font-family: 'Segoe UI', Arial, sans-serif;
            max-width: 1000px;
            margin: 0 auto;
            padding: 20px;
            line-height: 1.6;
            color: #333;
        }}
        h1 {{
            color: #6d132a;
            text-align: center;
            border-bottom: 3px solid #dcad73;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #6d132a;
            border-bottom: 1px solid #dcad73;
            padding-bottom: 5px;
        }}
        .subtitle {{
            text-align: center;
            color: #666;
            font-style: italic;
            margin-bottom: 30px;
        }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin: 20px 0;
        }}
        th, td {{
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }}
        th {{
            background-color: #6d132a;
            color: white;
        }}
        tr:nth-child(even) {{
            background-color: #f9f9f9;
        }}
        .chart {{
            text-align: center;
            margin: 20px 0;
        }}
        .chart img {{
            max-width: 100%;
            border: 1px solid #ddd;
            border-radius: 4px;
        }}
        .footer {{
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #666;
            font-size: 0.9em;
        }}
        .metric {{
            display: inline-block;
            background: #f5f5f5;
            padding: 10px 20px;
            margin: 5px;
            border-radius: 4px;
            border-left: 3px solid #6d132a;
        }}
        .metric-value {{
            font-size: 1.5em;
            font-weight: bold;
            color: #6d132a;
        }}
        .metric-label {{
            font-size: 0.9em;
            color: #666;
        }}
    </style>
</head>
<body>
    <h1>CiviQual Analysis Report</h1>
    <p class="subtitle">Generated: {datetime.now().strftime("%Y-%m-%d %H:%M")}</p>
    
    <h2>Data Summary</h2>
    <div>
        <div class="metric">
            <div class="metric-value">{len(data)}</div>
            <div class="metric-label">Total Observations</div>
        </div>
        <div class="metric">
            <div class="metric-value">{len(data.columns)}</div>
            <div class="metric-label">Columns</div>
        </div>
        <div class="metric">
            <div class="metric-value">{len(data.select_dtypes(include=['number']).columns)}</div>
            <div class="metric-label">Numeric Columns</div>
        </div>
    </div>
    
    <h2>Column Information</h2>
    <table>
        <tr>
            <th>Column Name</th>
            <th>Data Type</th>
            <th>Non-Null Count</th>
            <th>Null Count</th>
        </tr>
"""
        
        for col in data.columns:
            non_null = data[col].notna().sum()
            null_count = data[col].isna().sum()
            dtype = str(data[col].dtype)
            html += f"""        <tr>
            <td>{col}</td>
            <td>{dtype}</td>
            <td>{non_null}</td>
            <td>{null_count}</td>
        </tr>
"""
        
        html += """    </table>
"""
        
        # Add charts if provided
        if charts:
            html += """    <h2>Analysis Charts</h2>
"""
            for chart_path in charts:
                if Path(chart_path).exists():
                    # For HTML, we'll reference the image path
                    html += f"""    <div class="chart">
        <img src="{chart_path}" alt="Analysis Chart">
    </div>
"""
        
        html += f"""
    <div class="footer">
        <p>Generated by CiviQual Statistical Analysis Tool</p>
        <p>© 2025 A Step in the Right Direction LLC | www.qualityincourts.com</p>
    </div>
</body>
</html>
"""
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html)
        
        return str(output_path)
    
    def generate_user_guide(self, output_path):
        """
        Generate user guide document.
        
        Args:
            output_path: Path for output file
            
        Returns:
            str: Path to generated guide
        """
        if not DOCX_AVAILABLE:
            raise ImportError("python-docx is required. Install with: pip install python-docx")
        
        doc = Document()
        
        # Title
        title = doc.add_heading('CiviQual User Guide', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Subtitle
        subtitle = doc.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = subtitle.add_run('Workbench for Analysis, Testing, Statistics, Optimization & Navigation')
        run.italic = True
        
        doc.add_paragraph()
        
        # Version info
        version_para = doc.add_paragraph()
        version_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        version_para.add_run('Version 1.3.0 - Section 508 Accessibility Release')
        
        doc.add_page_break()
        
        # Table of Contents
        doc.add_heading('Table of Contents', level=1)
        toc_items = [
            '1. Introduction',
            '2. Getting Started',
            '3. CiviQual 4-Up Chart',
            '4. Descriptive Statistics',
            '5. Control Charts',
            '6. Capability Analysis',
            '7. ANOVA Analysis',
            '8. Pareto Analysis',
            '9. ROI Calculator',
            '10. Keyboard Shortcuts',
            '11. Accessibility Features'
        ]
        for item in toc_items:
            doc.add_paragraph(item)
        
        doc.add_page_break()
        
        # Chapter 1: Introduction
        doc.add_heading('1. Introduction', level=1)
        doc.add_paragraph(
            'CiviQual is a statistical analysis tool designed for Lean Six Sigma practitioners '
            'in government and public service organizations. It provides the analytical '
            'capabilities needed to complete DMAIC projects, replicating the methods taught '
            'in Lean Six Sigma training.'
        )
        
        doc.add_heading('About the Name', level=2)
        doc.add_paragraph(
            'CiviQual is named in honor of Dr. Gregory H. Watson, a leading international quality '
            'professional whose exploratory data analysis methodology forms the foundation of this tool. '
            'Dr. Watson developed the 4-Up Chart methodology—a variation of the Motorola Six Sigma '
            'Research Institute\'s exploratory data analysis framework.'
        )
        
        # Chapter 2: Getting Started
        doc.add_heading('2. Getting Started', level=1)
        
        doc.add_heading('Loading Data', level=2)
        doc.add_paragraph(
            'Click "Load Data File" or press Ctrl+O to open a data file. CiviQual supports '
            'CSV files (.csv) and Excel files (.xlsx, .xls). Your data should have column '
            'headers in the first row.'
        )
        
        doc.add_heading('Selecting Columns', level=2)
        doc.add_paragraph(
            'After loading data, select the column containing your measurement (Y measure) '
            'from the "Analysis Column" dropdown. For ANOVA analysis, also select a '
            'subgroup column.'
        )
        
        # Chapter 10: Keyboard Shortcuts
        doc.add_heading('10. Keyboard Shortcuts', level=1)
        
        shortcuts = [
            ('Ctrl+O', 'Open data file'),
            ('Ctrl+S', 'Save report'),
            ('Ctrl+G', 'Generate 4-Up Chart'),
            ('Ctrl+D', 'Run descriptive statistics'),
            ('Ctrl+I', 'Generate I-Chart'),
            ('Ctrl+P', 'Generate Pareto chart'),
            ('Ctrl+?', 'Show keyboard shortcuts'),
            ('F1', 'Show quick reference'),
            ('Ctrl+Tab', 'Switch to next tab'),
            ('Tab', 'Move to next control'),
            ('Alt+1 to Alt+9', 'Jump to tab 1-9')
        ]
        
        table = doc.add_table(rows=1, cols=2)
        table.style = 'Table Grid'
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Shortcut'
        hdr_cells[1].text = 'Action'
        
        for shortcut, action in shortcuts:
            row_cells = table.add_row().cells
            row_cells[0].text = shortcut
            row_cells[1].text = action
        
        # Chapter 11: Accessibility Features
        doc.add_heading('11. Accessibility Features', level=1)
        doc.add_paragraph(
            'CiviQual version 1.3 includes comprehensive accessibility features to meet '
            'Section 508 of the Rehabilitation Act and WCAG 2.0 Level AA standards:'
        )
        
        features = [
            'Full keyboard navigation',
            'Screen reader support with accessible names on all controls',
            'High-contrast focus indicators',
            'Label associations for form controls',
            'Tooltips on all input fields',
            'Compatible with NVDA, JAWS, and Windows Narrator'
        ]
        
        for feature in features:
            doc.add_paragraph(feature, style='List Bullet')
        
        # Footer
        doc.add_page_break()
        footer = doc.add_paragraph()
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.add_run('CiviQual User Guide\n').bold = True
        footer.add_run('© 2025 A Step in the Right Direction LLC\n')
        footer.add_run('www.qualityincourts.com')
        
        doc.save(output_path)
        return str(output_path)
